spring:
  application:
    name:store
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: postgres
  flyway:
    enabled: true
    clean-disabled: false
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,UZS
payment-gateway: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761